### ISSUE TITLE
Interactor?

### ISSUE THREAD

**Issue by grigoryfedorov** [Sandor13/Translator#10]
Тут довольно странный момент. Интерактор это бизнес логика. тут он во-первых в пакете view, во-вторых он занимается созданием репозитория. По-хорошему, ему в конструктор по интерфейсу должен приходить репозиторий. 

https://github.com/Sandor13/Translator/blob/0c918c5f6bb7025457b552feb9e3288f51175821/app/src/main/java/geekbrains/ru/translator/view/main/MainInteractor.kt#L17

**Comment by Sandor13** [comment]
Он в пакете вью, потому что я предпочитаю группировать классы по фичам, а не по слоям.
По репозиторию согласен, не очень чисто получилось. Переделаю.
