### ISSUE TITLE
Clean?

### ISSUE THREAD

**Issue by grigoryfedorov** [Sandor13/Translator#11]
Если придираться, то по тру клину данные должны мапиться между слоями. на это конечно можно частично забить. обычно упрощают, что entity из центрального слоя можно юзать везде, например во view. но тут другой кейс. 

https://github.com/Sandor13/Translator/blob/0c918c5f6bb7025457b552feb9e3288f51175821/app/src/main/java/geekbrains/ru/translator/model/data/SearchResult.kt#L5

**Comment by Sandor13** [comment]
Ну исключительно для упрощения, если честно. Иначе, по-хорошему, отдельные классы мапперов нужно писать и вот это вот все. У нас и так первые занятия сильно перегружены кодом и концепциями. Но делать так надо. Я придумал: у нас есть довольно пустой урок №7, который так и называется Рефакторинг и улучшения. Я лучше там уже все переведу на нормальные модели данных по слоям и буду мапить.
