### ISSUE TITLE
NetworkState

### ISSUE THREAD

**Issue by grigoryfedorov** [Sandor13/Translator#12]
Кажется этот класс не используется и устарел. сейчас рекомендуют https://developer.android.com/reference/android/net/ConnectivityManager.NetworkCallback.html

https://github.com/Sandor13/Translator/blob/0c918c5f6bb7025457b552feb9e3288f51175821/app/src/main/java/geekbrains/ru/translator/utils/NetworkStateChangeReceiver.kt#L10

**Comment by Sandor13** [comment]
ага, поправлю
