### ISSUE TITLE
по поводу BaseActivity

### ISSUE THREAD

**Issue by grigoryfedorov** [Sandor13/Translator#4]
Есть несколько вопросов :)
1. почему onPostCreate? довольно редко встречающийся метод и дока не особо рекомендует его юзать.
2. detachView не вызывается? допустим его нет особого смысла детачить, если презентер создается каждый раз (тогда можно и не атачить а сразу в конструктор передавать), но там ещё disposable очищается

https://github.com/Sandor13/Translator/blob/0c918c5f6bb7025457b552feb9e3288f51175821/app/src/main/java/geekbrains/ru/translator/view/base/BaseActivity.kt#L23

**Comment by Sandor13** [comment]
1. у меня, видимо, есть более свежий коммит, там я onResume использую. onPostCreate - это лажа какая-то была)
2. не совсем понял комментарий
