### ISSUE TITLE
выделение базового презентера

### ISSUE THREAD

**Issue by grigoryfedorov** [Sandor13/Translator#5]
не очень понятно, по какому принципу выделен базовый презентер. вероятно в следующих уроках станет понятнее, но на данный момент в базовом презентере, который, видимо, общий для всех экранов, есть как будто общая функция getData но с вполне конкретными параметрами для определенного экрана. 

https://github.com/Sandor13/Translator/blob/0c918c5f6bb7025457b552feb9e3288f51175821/app/src/main/java/geekbrains/ru/translator/presenter/BasePresenterImpl.kt#L22

**Comment by Sandor13** [comment]
да, у нас предполагается всего три экрана, два из которых имеют презентер и делят общий функционал. надо будет написать об этом в методичке
