### ISSUE TITLE
каст презентера

### ISSUE THREAD

**Issue by grigoryfedorov** [Sandor13/Translator#6]
неприятный каст к базовому презентеру. а если реализация вернет не базовый? при том, что везде в других местах упоминается базовый презентер. может быть обязать getPresenter тоже возвразать базовый и обойтись без каста?

https://github.com/Sandor13/Translator/blob/0c918c5f6bb7025457b552feb9e3288f51175821/app/src/main/java/geekbrains/ru/translator/view/base/BaseActivity.kt#L20

**Comment by Sandor13** [comment]
обязал, но из-за "the following declarations have the same jvm signature" (Котлин ругается на одинаковые сигнатуры var presenter и fun createPresenter()) пришлось сделать var presenter приватным и написать для него явный геттер. Насколько это лучше кастинга и есть ли более нормальное решение?

abstract class BaseActivity<T : DataModel> : AppCompatActivity(), View {

    **private lateinit var presenter: BasePresenterImpl<T, View>**

    protected abstract fun createPresenter(): BasePresenterImpl<T, View>

    abstract override fun renderData(dataModel: DataModel)

    **protected fun getPresenter(): BasePresenterImpl<T, View> {
        return presenter
    }**

    override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)
        presenter = createPresenter()
    }

    override fun onResume() {
        super.onResume()
        presenter.attachView(this)
    }

    override fun onDestroy() {
        super.onDestroy()
        presenter.detachView(this)
    }
}
