### ISSUE TITLE
MVP?

### ISSUE THREAD

**Issue by grigoryfedorov** [Sandor13/Translator#7]
Тут используется подход, который мне сразу MVI напоминает) 
тот MVP, который мне знаком, предполагает, что презентер вызывает методы вьюхи через интерфейс, раздельно дергая когда надо методы загрузки, ошибки, показа данных. и методы презентера не возвращают никаких значений. 
я не утверждаю, что это плохое решение, но вроде это не MVP )

https://github.com/Sandor13/Translator/blob/0c918c5f6bb7025457b552feb9e3288f51175821/app/src/main/java/geekbrains/ru/translator/presenter/BasePresenterImpl.kt#L22

**Comment by Sandor13** [comment]
Это уже второй урок? Потому что в первом у меня Презентер так и делает - дергает методы View. Я по аналогии с MVI делаю - передаю модель данных, но разницы никакой нет - Презентер управляет View. На втором уроке я сначала добавляю в Презентер LiveData и затем полностью перехожу на ViewModel вместо Презентера. Вроде все последовательно. Или нет?
