### ISSUE TITLE
еще каст

### ISSUE THREAD

**Issue by grigoryfedorov** [Sandor13/Translator#8]
Тут уж совсем какой-то неприятный каст. наверное можно как-то конкретизировать тип? 

https://github.com/Sandor13/Translator/blob/0c918c5f6bb7025457b552feb9e3288f51175821/app/src/main/java/geekbrains/ru/translator/view/main/MainActivity.kt#L50

**Comment by Sandor13** [comment]
Я согласен, но мне кажется тут от него не избавиться. Это конкретный вью, с конкретным презентером, которые работают с конкретными данными. Как ты предлагаешь его конкретизировать?
