### ISSUE TITLE
companion object вверху?

### ISSUE THREAD

**Issue by grigoryfedorov** [Sandor13/Translator#9]
есть code style, который предполагает companion object размещать вверху класса, тогда больше похоже на константы в Java. мне кажется в этом есть смысл.
Студентов не так учат? 

https://github.com/Sandor13/Translator/blob/0c918c5f6bb7025457b552feb9e3288f51175821/app/src/main/java/geekbrains/ru/translator/view/main/MainActivity.kt#L107

**Comment by Sandor13** [comment]
https://kotlinlang.org/docs/reference/coding-conventions.html#class-layout
вроде внизу всегда) Котлину похер на статику)
